### PR TITLE
Implement a RGB and YCbCr converter 

### PR DESCRIPTION
**Pull request by tukaramhl**
Related to [Issue #47 ](https://github.com/Sistemas-Multimedia/MCDWT/issues/47)

Change log:
-Added ImageColorConveter class to /mcdwt/image_io.py
-Changed /tests/test_png.py code to check all the functions in image_io.py

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @tukaramhl . Thanks for the PR. However, I have a couple of requests. (1) You have replaced the code to test if the PNG format is suitable for storing 16 bpp/component images (`tests/test_png.py`) by the RGB to YCbCb converter. I would prefeer that you create a couple of scripts called `rgb2yuv` and `yuv2rgb` in a (new) `tools` directory. And (2), I think also that adding the code to convert the images to the file `mcdwt/image_io.py` is not the better option. I would create a new library file called for example, `rgb_yuv_conversion.py` in the `mcdwt` directory. Please, could you carry out these modifications and generate a new PR?

Tons of thanks!

**Comment by tukaramhl** [comment]
Sure, no problem. I'm closing this PR then.

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @tukaramhl !

Great job. However, I have two requests (before accepting your PR):

1. Please, create a script in the directory `tools` (update from the master branch) to convert the images between both color domain. This is the main propose of this issue.

2. I would prefer to keep the test script `test_png.py` as it is. It only asserts that using 16 PNG is OK for our goals and it should keep this behavior.

And a final question. I also prefer to generate the temporal files (such as those generated in `../images/output/') outside of the MCDWT directory. If you see for example `test_png.py`, the temporal files are created in `/tmp/`. This is a directory that in Unix systems is always available.

The question is, supposing that some of you work in Windows, is it possible to create this directory and run for example, `test_png.py`?

Thanks!
Vicente.

**Comment by tukaramhl** [comment]
I've created a couple of standalone scripts that accept an input and an output file, but I'm not sure that's what you are looking for. About the "temp" directory, I've been looking at [this library](https://docs.python.org/3/library/tempfile.html). The `gettempdir()` function could be useful but I have yet to test it on Windows.

**Comment by vicente-gonzalez-ruiz** [comment]
Thank you very much!

**Comment by vicente-gonzalez-ruiz** [comment]
Maybe you could create a new issue for checking the `gettempdir()` function :-)

**Pull request merged**
