### PR TITLE
Close issue 12

### PR DESCRIPTION
**Pull request by PakitOliva**

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Some unuseful files are included. Please, remove them.

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @PakitOliva . Sorry but I'm sure if you have finished this issue. Have you done it?

**Comment by PakitOliva** [comment]
Yes. You can close this issue.

**Comment by vicente-gonzalez-ruiz** [comment]
Thanks!

**Pull request merged**
